# Initialize CXXFLAGS.
if (NOT ${CMAKE_CXX_COMPILER_ID} STREQUAL "MSVC")
  set(CMAKE_CXX_FLAGS "-Wall -Wextra ${CMAKE_CXX_FLAGS}")
endif()
if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND
    CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(CMAKE_CXX_FLAGS "-ggdb3 ${CMAKE_CXX_FLAGS}")
endif()
if (MSVC)
  add_definitions(/D_SCL_SECURE_NO_WARNINGS /D_CRT_SECURE_NO_WARNINGS)
endif()
